swagger: "2.0"
consumes:
- application/json
info:
  description: Manage Projects
  title: Create and Display available projects
  version: 1.0.0
paths:
  /projects:
    get:
      tags:
        - projects
      responses:
        200:
          description: list all the current projects
          schema:
            type: array
            items:
              $ref: "#/definitions/project"
        default:
          description: generic error response
          schema:
            $ref: "#/definitions/error"
    post:
      tags:
        - projects
      operationId: addOne
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/project"
      responses:
        201:
          description: Created
          schema:
            $ref: "#/definitions/project"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /projects/{uuid}:
    delete:
      tags:
        - projects
      operationId: destroyOne
      parameters:
        - type: string
          name: uuid
          in: path
          required: true
      responses:
        204:
          description: Deleted
        default:
          description: error
          schema:
            $ref: "#/definitions/error"

produces:
- application/json
schemes:
- http
definitions:
  project:
    type: object
    required:
      - name
    properties:
      uuid:
        type: string
        format: uuid
        readOnly: true
      name:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code: 
        type: integer
        format: int32
      message:
        type: string
        minLength: 1